language: node_js
node_js:
  - node
  - '6'
os:
  - linux
after_success: npm run coveralls
jobs:
  include:
    - stage: npm release
      node_js: '6'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key:
          secure: >-
            EBluN/+mvz7JTi3sxUFaa8YGf/w72MRg5UkCTT4AuzzXlXaM40YQidLlDMmKaZ0AkX6L8ElHWucUfcf3mV3boVuVwplhi68gqiX4iQQ4uFDMghDfzMqrcDzQfrIUOt+47OBFeWdU8SiRMTf/ItIskeO8T1NAxkI0OumCblC0DP/2ouSfhVtGvksMHvA7HNczzxdMEwd5w60Pr+tpvUorRXOqn2uC+tL5n47/tUBidjgZZ7NUfMTJMBwiHidY3SKp3K9fbQULEl9tQVeBSFe+u6SI6iNXiR1RkJ/yoSV/9FIE8+kbCHCvMTHt3Qn8Kl6cn2hxJdHvxzxlIZF3Ym9xDQNF7n2TJtjv1AsD1NerTLAMf+jZJY5l+4wly7tGhp5OGNfpfMH8/oy0flmEzjWnklLJaUNn7yXFdOe4vqpCsbIkTftoFc5Ki0RXck4DJxHR8NTAysHjF5z56wDfsw4F4NgirhmIqvaLlJGpzqHfeVhctL0/pM2ljloxS+mgcMxXF/rQdteoZIYhvFgjFN+TqOImeL7B2t8tihZ4/rJoH2HlMvkmAeTR4SPUTqNsZBsRE0kEAts5AtsbGb18lju4fZ+petkGCZWhwHiJjhYtsI75WStzNkZFRHuVgvOOgx01j6M30I9uZbiJUamI40yg5ocvYAKoiT5Anf64ADuvc2w=
        'on':
          branch: master
        skip_cleanup: true
